### ISSUE TITLE
publish jars to Maven

### ISSUE THREAD

**Issue by blbradley** [qubole/streamx#11]
Hello! Thanks for your work.

Could you publish this to Maven? It would help many of your users.

Cheers!

**Comment by PraveenSeluka** [comment]
Hi @blbradley 

Thanks, we will get that done. We are working on dockerizing streamx too (which makes it easier to get started)

Thanks

**Comment by jocelyndrean** [comment]
HI @PraveenSeluka , I'm thinking about working on a way to dockerizing Kafka connect + streamx. Is someone already worked on it ? :)

**Comment by PraveenSeluka** [comment]
HI @jocelyndrean I have done some work on it already. So, I will push those changes soon. You can try it out and add features if necessary.

**Comment by blbradley** [comment]
@jocelyndrean Confluent released a set of [images](https://github.com/confluentinc/cp-docker-images) for Kafka Platform that are great.

**Comment by PraveenSeluka** [comment]
@jocelyndrean I believe you have checked it out already. We added dockerfile to repo, enables you to build streamx image now.

**Comment by blbradley** [comment]
Docker images are a great way to run connectors. I consider this issue closed.

Bring up another issue if the Docker images don't work.
