### ISSUE TITLE
Why only last append is taken from rds when applying a wal ???

### ISSUE THREAD

**Issue by bbnsumanth** [qubole/streamx#2]
I was going through the code of RDSWal and bumped into a doubt.Why only last record is taken from rds table for a topicPartition to make a commit.Since a single topicPartition can write data to multiple files (tempFiles) based on partitioner logic we use,I guess there is a chance that we might not commit all the temp files upon wal apply.Any clarification on this this highly appreciated.

**Comment by PraveenSeluka** [comment]
This issue is resolved now. If one topicPartition writes to multiple files based on custom partitioner, it will concat all the tempFiles in comma separated fashion and store it as 1 record in database. Let me know if this sounds good.
