### ISSUE TITLE
JSON messages not legible in S3 saved files

### ISSUE THREAD

**Issue by janie128** [qubole/streamx#21]
Hi,

I saw in an earlier issue that there is now support for JSON format. I have followed the README instructions, using
`key.converter=com.qubole.streamx.ByteArrayConverter value.converter=com.qubole.streamx.ByteArrayConverter`
and
`"format.class":"com.qubole.streamx.SourceFormat"`

Files are being successfully saved to S3, however, their content are not legible strings, eg.
`^A^@^@^@^A^»¯,Ú^OB^V^@^@^@^@^@^@^@x`

It seems in the file `SourceRecordWriterProvider.java`, it is directly writing bytes. Is it converted somewhere to string?

Thanks!

**Comment by PraveenSeluka** [comment]
Hi @janie128 

It does not do any conversion to String. It just writes out the bytes. Can you tell how you publish data to Kafka ?

Thanks

**Comment by janie128** [comment]
Hi @PraveenSeluka 

I am simply using the `kafka-console-producer.sh`, and inputting messages like `{"schema":{"type":"string","optional":false},"payload":{"res":"1"}}`

The temp `block_someNumber` files have the correct messages as legible strings. It's the final files that are save in the location specified in the config "s3.url" that are garbled.

Thanks

**Comment by janie128** [comment]
@PraveenSeluka 
I'm trying to understand when and how those `block_` files are being saved. They're being saved in the root of the bucket I specify (my s3.url is `s3://myBucket/streamX`).

I modified the code to log the `tempFile` in the `commitFile` function in `TopicPartitionWriter.java`, and its output is `s3://myBucket/streamX/topics/+tmp/myTopic/partition=0/tmpFileName`. Where as the `committedFile` is `s3://myBucket/streamX/topics/myTopic/partition=0/fileNameWithPartition`.

The files in `s3://myBucket/streamX/topics/myTopic/partition=0/` have garbled content, but the `block_` files in `s3://myBucket/` are the actual records that went through Kafka, as legible strings.

I don't really understand why the `block_` files have the correct content but then the final files don't. Could you please help / explain?

Thank you!

**Comment by PraveenSeluka** [comment]
Hi @janie128 

I am not aware of these block_ files. It must only be creating the tempFile and committedFile. May be, those block_ files are generated by something outside of StreamX ? (Can you check)

Thanks

**Comment by janie128** [comment]
Hi @PraveenSeluka 
I'm not quite sure how to check to be honest. My guess is that it's produced through however the write operation to HDFS is implemented. I have not been able to find this explicitly in the source code.

Aside from that though, is there a reason you implemented the write to file as directly writing bytes and not strings? Should I not be expecting legible files saved to the `committedFile`?

Thanks!

**Comment by PraveenSeluka** [comment]
Hi @janie128 

Just want to cross check this. Did you specify these parameters "key.converter" and "value.converter" in Job request or connect-distributed.properties ? It has to be in connect-distributed.properties (I doubt that this is not set, and hence its picking JsonConverter default and that has issues)

Thanks
Praveen

**Comment by janie128** [comment]
Hi @PraveenSeluka 

I specified those parameters in `connect-distributed.properties`. And the `format.class` was set in the REST endpoint request. 

Thanks,
Janie

**Comment by PraveenSeluka** [comment]
@janie128 Since ByteArrayConverter along with SourceFormat can copy data as-is, can you try sending some other non JSON message to validate ?

**Comment by janie128** [comment]
Hi @PraveenSeluka 

I sent simple string messages of `a`, `b`... The committed file is still garbled.
I want to clarify something - since StreamX is writing bytes directly, and there's no conversion to String performed, am I supposed to be able to see string messages in my committed file? Or do I have to do further processing on these files.

Thanks,
Janie

**Comment by PraveenSeluka** [comment]
Hi @janie128 

It will help if you send the following.
- kafka-console-producer command line (this should be using the default ByteArraySerializer for value-serializer)
- connect-distributed.properties
- job config

You dont need any further processing of files, you must be able to see the messages. Can you try running kafka-console-consumer and check if the messages are garbled there ?

Thanks
Praveen

**Comment by janie128** [comment]
Hi @PraveenSeluka 

For the producer, I'm using the cli, so running:
`bin/kafka-console-producer.sh --topic myTopic --broker-list $KAFKA_IP:9092`
and then inputting messages such as 
`{"schema":{"type":"string","optional":false},"payload":{"res":"1"}}` or most recently, simply `a`, `b`...

connect-distributed.properties:
`bootstrap.servers=$KAFKA_IP:9092`
`group.id=connect-cluster`
`key.converter=com.qubole.streamx.ByteArrayConverter`
`value.converter=com.qubole.streamx.ByteArrayConverter`
`internal.key.converter=org.apache.kafka.connect.json.JsonConverter`
`internal.value.converter=org.apache.kafka.connect.json.JsonConverter`
`internal.key.converter.schemas.enable=false`
`internal.value.converter.schemas.enable=false`
`offset.storage.topic=connect-offsets`
`config.storage.topic=connect-configs`
`status.storage.topic=connect-status`
`offset.flush.interval.ms=10000`

The REST API job config:
`{"name":"teststream",`
`"config":`
`{`
`"name":"teststream",`
`"connector.class":"com.qubole.streamx.s3.S3SinkConnector",`
`"format.class":"com.qubole.streamx.SourceFormat",`
`"tasks.max":"1",`
`"topics":"myTopic",`
`"flush.size":"2",`
`"s3.url":"s3://myBucket/streamX",`
`"hadoop.conf.dir":"/data/hadoop-conf"`
`}}`

Messages received through kafka-console-consumer and also the FileStreamSink are both fine and legible. It's even legible in those `block_` files that are saved to s3 as well.

Thanks,
Janie

**Comment by PraveenSeluka** [comment]
@janie128 all the configs look good. Am wondering what s3 file system are you using. Are you using the old s3 block file system by any chance ? (block_ files may be due to this)

**Comment by PraveenSeluka** [comment]
@janie128 https://github.com/qubole/streamx/blob/master/config/hadoop-conf/hdfs-site.xml - check this hadoop-conf hdfs-site.xml to use S3AFileSystem. Try that out

**Comment by janie128** [comment]
@PraveenSeluka 
Yes that was absolutely the problem!
I did not have this
`<name>fs.s3.impl</name>`
`<value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>`
and so it was defaulting to the s3 file system.

It works perfectly fine now, and no `block_` files either.
Thanks very much for your help and for this library!

Best,
Janie

**Comment by PraveenSeluka** [comment]
ok great to know it works. Thanks for using StreamX
