### ISSUE TITLE
Parquet and Hive integration - Example job configuration

### ISSUE THREAD

**Issue by jocelyndrean** [qubole/streamx#23]
Hello Guys,
Thank you so much for this amazing project ! Really a good job :)
I'm really sorry for this stupid issue, but: Is anyone got a configuration example for :
- a job that uses Hive Integration (where the connector creates partitioned hive table and periodically does add partitions once it writes a new partition to s3)
- a job that writing data in Parquet (or Avro) formats

Thank so much for your help :)
Have a nice day,
Jocelyn

**Comment by PraveenSeluka** [comment]
Hi @jocelyndrean 

Very happy to know that StreamX helps. Here is a sample configuration
```
{"name":"s3connect",
 "config":
{
"connector.class":"com.qubole.streamx.s3.S3SinkConnector",
"tasks.max":"1",
"flush.size":"3000",
"s3.url":"s3://streamx/demo/",
"hadoop.conf.dir":"/usr/lib/hadoop2/etc/hadoop/",
  "topics":"clickstream",
"rotate.interval.ms":"60000",
"partitioner.class":"io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner",
"partition.duration.ms":"3600000",
"path.format":"'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH/",
"locale":"en",
  "timezone":"GMT",
  "hive.metastore.uris":"thrift://localhost:10000",
  "hive.integration":"true",
  "schema.compatibility":"BACKWARD"
}}
```

In general, users like to add hourly partitions. The above config will create a new partition every 3600000  ms (1 hour). It will have "s3://streamx/demo/topics/clickstream/year=2016/month=09/day=21/hour=22/" as directory. 

Regarding hive integration, it packages the required hive dependencies. You need a hive metastore server running somewhere and point streamx to that. Every 1 hour, it will do add partition call to update the hive table.

In connect-distributed.properties,

You need to use AvroConverter and SchemaRegistry to store Avro schemas. (Avro message in Kafka, and Avro output to s3)
```

key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
```

Let us know if you need any more information.

Thanks
Praveen

**Comment by jocelyndrean** [comment]
Hello Praveen,

Thank you so much for your answer. I tested with this configuration and this is working perfectly :)

Amazing job on this project guys ! Thanks !

Jocelyn
