### ISSUE TITLE
Dockerize StreamX

### ISSUE THREAD

**Issue by PraveenSeluka** [qubole/streamx#24]

**Comment by jocelyndrean** [comment]
Hey @PraveenSeluka. Thanks for your PR with Docker :) I will also add a new PR soon to add a new env var "CONNECT_USE_AVRO" (with a default value to false ) to handle avro support if it sounds good for you.
If you have a better name for this var, I take it ! :)

**Comment by PraveenSeluka** [comment]
Hi @jocelyndrean 

Use AVRO will replace the key.converter and value.converter properties ? If so, name that CONNECT_KEY_CONVERTER and CONNECT_VALUE_CONVERTER. The convention is to prefix with CONNECT and add the property name itself. This must work right now as it-is. 

In addition, this will require schema registry related properties also. Currently the utils.py will only replace existing properties with new values, but does not add new properties. We need to extend that to add new properties if it does not exist.

Go ahead and submit a PR, I will be happy to take that in.

**Comment by jocelyndrean** [comment]
What I had in mind:
- add a new file "/config/connect-avro-distributed.properties"
- add a boolean var CONNECT_USE_AVRO to switch from "connect-distributed.properties" to "connect-avro-distributed.properties"
So no need to extend that to add new properties if it does not exist.

What do you think about this approach ?

**Comment by jocelyndrean** [comment]
@PraveenSeluka, I created a PR : https://github.com/qubole/streamx/pull/27
Please, fell free to merge or to give me some feedback :)

**Comment by PraveenSeluka** [comment]
@jocelyndrean thanks for the PR. Lets take the discussion tehre. I am closing this ticket
