### ISSUE TITLE
Problem with reassignment of tasks when running in a distributed mode.

### ISSUE THREAD

**Issue by bbnsumanth** [qubole/streamx#3]
Since copying data is done from local to s3,How to deal with partition reassignments when running in a distributed mode?? Sink task for a particular topic partition can run on a different machine after partition reassignment and the recovery to be done after partition reassignment will fail because wal append couldn't find the file on new local storage.

**Comment by PraveenSeluka** [comment]
Hi @bbnsumanth thanks for your interest in this. The recovery flow will check if the last entry in WAL is available in s3(using file read check and not list, as list is eventually consistent in s3). If not, it will actually use the last but one entry in WAL (it wont be able to recover the local file written, as it can be in a different node). I will be adding these changes this week. Can you share your email (mine is pseluka@qubole.com), I can send you the design doc by this week

**Comment by bbnsumanth** [comment]
thanks for your reply.I can be reached on sumanth.b@roadrunnr.in . Design doc will be very helpful.

**Comment by PraveenSeluka** [comment]
We have made the WAL changes and currently it writes the tempFile to s3 itself. We will be introducing and optimization to write it to local file system instead (but this will not guarantee exactly-once delivery. there is a small corner case that can result in duplicate data)
