### ISSUE TITLE
Question: Do you regularly merge kafka-connect-hdfs updates to your fork?

### ISSUE THREAD

**Issue by phillipamann** [qubole/streamx#33]
I see there is lots of development that happens with kafka-connect-hdfs.  I have been building a solution with your S3 connector as we are on S3 and not HDFS anymore.  As I continue development before deploying to production (I am working on my own custom partitioner), I would love to have the latest updates from kafka-connect-hdfs as well as the latest updates to your own S3 connector.  What are your own reasons for not merging the latest kafka-connect-hdfs changes to your fork?

**Comment by PraveenSeluka** [comment]
Hi @phillipamann We want to update it regularly. We have a plan to pull in new changes from kafka-connect-hdfs after every confluent minor release. Does that sound good to you ?

**Comment by phillipamann** [comment]
Sure (I think...).  Do you have an explicit plan linked somewhere?  I noticed that in your POM, you have older (non minor release) versions of CP and Kafka.  This is why I asked.

**Comment by PraveenSeluka** [comment]
Ya till now, I have done manual merges whenever I find time or something needs to get pulled in. I have been thinking on this for sometime. Will send out a plan.

**Comment by phillipamann** [comment]
Is there a way I can contribute?

**Comment by PraveenSeluka** [comment]
@phillipamann it will be great if you could help in merge or adding some tests to StreamX. Both are very important. One thing I want to make sure before the merge is, that its backward compatible with older versions of Kafka/Confluent,

**Comment by levin81** [comment]
Hi, didn't want to open a separate issue for this but I would love the `rotate.schedule.interval.ms` option to be merged from the hdfs connector (implemented in 3.1.x) into streamx.

**Comment by PraveenSeluka** [comment]
@levin81 Sure, I will look into upgrading soon.

**Comment by PraveenSeluka** [comment]
@phillipamann I have done the upgrade and doing some testing. I can push it as a separate branch if you would like to test it out first.

**Comment by PraveenSeluka** [comment]
@phillipamann I have done the upgrade. Can you try it out.

**Comment by PraveenSeluka** [comment]
I am closing this issue. If you find any issues with upgrade, please file an issue. Thanks

**Comment by OneCricketeer** [comment]
Are you the only one that maintains this @PraveenSeluka ?
