### ISSUE TITLE
What is the ideal number for flush.size?

### ISSUE THREAD

**Issue by phillipamann** [qubole/streamx#34]
This is not really clear.  Is there an ideal number to set for flush.size when writing to S3?

**Comment by PraveenSeluka** [comment]
There is no ideal number actually. Its a trade-off between how soon you need the data in s3 and how big the files you need.

- if you dont need the data quickly, a larger flush.size is preferred. Once the data is in s3, if its used for analytics purpose, its better to have larger files as most analytical engines have issues with small files. (s3 listing can get very expensive when you have 10's of 1000's of files)

- Other option is to use rotate.interval.ms which is time based rotation.

**Comment by PraveenSeluka** [comment]
@phillipamann can I close this issue or do you need anything else ?

**Comment by phillipamann** [comment]
You may close the issue.  I am sorry for my delay in replying to you lately.  I have been so busy at work with things not related to Kafka Connect.  We'll touch base soon.

**Comment by PraveenSeluka** [comment]
Sure @phillipamann
