### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by alexanderdean** [qubole/streamx#5]
The current name is completely un-SEOable. Why not kafka-connect-object-stores or kafka-connect-cloud-blobs

**Comment by PraveenSeluka** [comment]
Hi @alexanderdean, thanks for the feedback. Although this project will provide support for all major clouds, if you are a s3 user - you would search for "kafka-connect-s3" (and thats already taken) and mostly not kafka connect object/blob store. So not sure if that would have helped a lot. 

I have added kafka-connect-s3 to the description and hopefully expand README with more s3 specific details soon - it might help a little.

**Comment by alexanderdean** [comment]
Thanks @PraveenSeluka - that seems like a good compromise. I'd also suggest updating the h1 in the README, maybe:

### StreamX: Kafka Connect for S3

**Comment by PraveenSeluka** [comment]
ok @alexanderdean sure - will make this change.
